// instant.schema.ts
// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from '@instantdb/react';

const _schema = i.schema({
    entities: {
        $files: i.entity({
            path: i.string().unique().indexed(),
            url: i.string(),
        }),
        $users: i.entity({
            email: i.string().unique().indexed().optional(),
            imageURL: i.string().optional(),
            type: i.string().optional(),
        }),
        allowanceEnvelopes: i.entity({
            amount: i.any().optional(),
            balances: i.any().indexed(),
            currency: i.any().optional(),
            description: i.string().optional(),
            goalAmount: i.number().optional(),
            goalCurrency: i.string().optional(),
            isDefault: i.boolean(),
            name: i.string(),
        }),
        allowanceTransactions: i.entity({
            amount: i.number(),
            createdAt: i.string().indexed(),
            createdBy: i.string().indexed().optional(),
            createdByFamilyMemberId: i.string().indexed().optional(),
            currency: i.string(),
            description: i.string(),
            transactionType: i.string(),
            updatedAt: i.string(),
        }),
        calculatedAllowancePeriods: i.entity({
            calculatedAmount: i.number(),
            completedWeight: i.number(),
            familyMemberId: i.string().indexed(),
            isStale: i.boolean().indexed(),
            lastCalculatedAt: i.date(),
            percentage: i.number(),
            periodEndDate: i.date().indexed(),
            periodStartDate: i.date().indexed(),
            totalWeight: i.number(),
        }),
        calendarItems: i.entity({
            alarms: i.json().optional(),
            attendees: i.json().optional(),
            conferenceData: i.json().optional(),
            createdAt: i.string().indexed().optional(),
            dayOfMonth: i.number().indexed(),
            description: i.string().optional(),
            dtStamp: i.string().indexed().optional(),
            endDate: i.string(),
            eventType: i.string().indexed().optional(),
            exdates: i.json().optional(),
            isAllDay: i.boolean(),
            lastModified: i.string().indexed().optional(),
            location: i.string().optional(),
            month: i.number().indexed(),
            organizer: i.json().optional(),
            priority: i.number().indexed().optional(),
            recurrenceId: i.string().indexed().optional(),
            recurrenceIdRange: i.string().optional(),
            recurrenceLines: i.json().optional(),
            recurringEventId: i.string().indexed().optional(),
            rdates: i.json().optional(),
            rrule: i.string().indexed().optional(),
            sequence: i.number().indexed().optional(),
            sourceAccountKey: i.string().indexed().optional(),
            sourceCalendarId: i.string().indexed().optional(),
            sourceCalendarName: i.string().optional(),
            sourceExternalId: i.string().unique().indexed().optional(),
            sourceImportedAt: i.string().indexed().optional(),
            sourceLastSeenAt: i.string().indexed().optional(),
            sourceReadOnly: i.boolean().indexed().optional(),
            sourceRemoteCtag: i.string().indexed().optional(),
            sourceRemoteEtag: i.string().indexed().optional(),
            sourceRemoteUrl: i.string().optional(),
            sourceRawHash: i.string().indexed().optional(),
            sourceSyncStatus: i.string().indexed().optional(),
            sourceType: i.string().indexed().optional(),
            startDate: i.string(),
            status: i.string().indexed().optional(),
            timeZone: i.string().indexed().optional(),
            title: i.string(),
            transparency: i.string().indexed().optional(),
            travelDurationAfterMinutes: i.number().optional(),
            travelDurationBeforeMinutes: i.number().optional(),
            uid: i.string().unique().indexed().optional(),
            updatedAt: i.string().indexed().optional(),
            url: i.string().optional(),
            visibility: i.string().indexed().optional(),
            xProps: i.json().optional(),
            year: i.number().indexed(),
        }),
        calendarTags: i.entity({
            createdAt: i.string().indexed().optional(),
            name: i.string(),
            normalizedName: i.string().unique().indexed(),
            updatedAt: i.string().indexed().optional(),
        }),
        choreAssignments: i.entity({
            order: i.number(),
        }),
        calendarSyncAccounts: i.entity({
            accountLabel: i.string(),
            appleCalendarHomeUrl: i.string().optional(),
            applePrincipalUrl: i.string().optional(),
            createdAt: i.string().indexed(),
            lastAttemptedSyncAt: i.string().indexed().optional(),
            lastErrorAt: i.string().indexed().optional(),
            lastErrorCode: i.string().optional(),
            lastErrorMessage: i.string().optional(),
            lastSuccessfulSyncAt: i.string().indexed().optional(),
            passwordCiphertext: i.string(),
            passwordKeyVersion: i.string(),
            provider: i.string().indexed(),
            repairScanIntervalHours: i.number().optional(),
            selectedCalendarIds: i.json().optional(),
            status: i.string().indexed(),
            syncWindowFutureDays: i.number().optional(),
            syncWindowPastDays: i.number().optional(),
            updatedAt: i.string().indexed(),
            username: i.string(),
        }),
        calendarSyncCalendars: i.entity({
            accountId: i.string().indexed(),
            color: i.string().optional(),
            createdAt: i.string().indexed(),
            description: i.string().optional(),
            displayName: i.string(),
            isEnabled: i.boolean().indexed(),
            lastCtag: i.string().optional(),
            lastSeenAt: i.string().indexed().optional(),
            lastSuccessfulSyncAt: i.string().indexed().optional(),
            lastSyncToken: i.string().optional(),
            remoteCalendarId: i.string().indexed(),
            remoteUrl: i.string().optional(),
            timeZone: i.string().optional(),
            updatedAt: i.string().indexed(),
        }),
        calendarSyncLocks: i.entity({
            createdAt: i.string().indexed(),
            expiresAt: i.string().indexed(),
            key: i.string().unique().indexed(),
            owner: i.string(),
        }),
        calendarSyncRuns: i.entity({
            accountId: i.string().indexed(),
            calendarsProcessed: i.number().optional(),
            details: i.json().optional(),
            durationMs: i.number().optional(),
            errorCode: i.string().optional(),
            errorMessage: i.string().optional(),
            eventsCancelled: i.number().optional(),
            eventsCreated: i.number().optional(),
            eventsMarkedDeleted: i.number().optional(),
            eventsUnchanged: i.number().optional(),
            eventsUpdated: i.number().optional(),
            finishedAt: i.string().indexed().optional(),
            provider: i.string().indexed(),
            remoteEventsFetched: i.number().optional(),
            startedAt: i.string().indexed(),
            status: i.string().indexed(),
            trigger: i.string().indexed(),
        }),
        choreCompletions: i.entity({
            allowanceAwarded: i.boolean().indexed(),
            completed: i.boolean(),
            dateCompleted: i.string().optional(),
            dateDue: i.string(),
        }),
        chores: i.entity({
            advanceCompletionLimit: i.any().optional(),
            allowExtraDays: i.any().optional(),
            area: i.any().optional(),
            canCompleteInAdvance: i.any().optional(),
            canCompletePast: i.any().optional(),
            description: i.string().optional(),
            difficultyRating: i.any().optional(),
            done: i.boolean(),
            dueTimes: i.any().optional(),
            exdates: i.json().optional(),
            imageUrl: i.any().optional(),
            isUpForGrabs: i.boolean().optional(),
            isJoint: i.boolean().optional(),
            pauseState: i.json().optional(),
            pastCompletionLimit: i.any().optional(),
            rewardAmount: i.number().optional(),
            rewardCurrency: i.string().optional(),
            rewardType: i.string().optional(),
            rotationType: i.string(),
            rrule: i.string().optional(),
            startDate: i.string(),
            title: i.string(),
            weight: i.number().optional(),
        }),
        exchangeRates: i.entity({
            baseCurrency: i.string().indexed(),
            lastFetchedTimestamp: i.date().indexed(),
            rate: i.number(),
            targetCurrency: i.string().indexed(),
        }),
        familyMembers: i.entity({
            allowanceAmount: i.number().optional(),
            allowanceConfig: i.json().optional(),
            allowanceCurrency: i.string().optional(),
            allowancePayoutDelayDays: i.number().optional(),
            allowanceRrule: i.string().optional(),
            allowanceStartDate: i.date().optional(),
            color: i.string().optional(),
            email: i.string().indexed().optional(),
            lastDisplayCurrency: i.string().optional(),
            name: i.string(),
            order: i.number().indexed(),
            photoUrls: i.json().optional(),
            role: i.string().optional(), // 'parent' or 'child'
            pinHash: i.string().optional(),
            viewShowChoreDescriptions: i.boolean().optional(),
            viewShowTaskDetails: i.boolean().optional(),
        }),
        settings: i.entity({
            name: i.string(),
            value: i.string(),
        }),
        taskAttachments: i.entity({
            createdAt: i.date(),
            name: i.string(),
            type: i.string(),
            updatedAt: i.date(),
            url: i.string(),
        }),
        tasks: i.entity({
            createdAt: i.date().optional(),
            indentationLevel: i.number().optional(),
            isDayBreak: i.boolean(),
            isCompleted: i.boolean().optional().indexed(),
            completedAt: i.date().optional(),
            completedOnDate: i.string().optional().indexed(),
            childTasksComplete: i.boolean().optional(),
            notes: i.string().optional(),
            order: i.number(),
            overrideWorkAhead: i.boolean().optional(),
            specificTime: i.string().optional(),
            text: i.string(),
            updatedAt: i.date().optional(),
        }),
        taskSeries: i.entity({
            breakDelayUnit: i.string().optional(),
            breakDelayValue: i.number().optional(),
            breakStartDate: i.date().optional(),
            breakType: i.string().optional(),
            createdAt: i.date().optional(),
            description: i.string().optional(),
            dependsOnSeriesId: i.string().optional().indexed(),
            name: i.string(),
            startDate: i.date().optional(),
            targetEndDate: i.date().optional(),
            updatedAt: i.date().optional(),
            workAheadAllowed: i.boolean().optional(),
        }),
        timeOfDayDefinitions: i.entity({
            endTime: i.string(),
            name: i.string(),
            startTime: i.string(),
        }),
        todos: i.entity({
            createdAt: i.any(),
            done: i.boolean(),
            text: i.any(),
        }),
        unitDefinitions: i.entity({
            code: i.string().unique().indexed(),
            decimalPlaces: i.number().optional(),
            isMonetary: i.boolean().indexed(),
            name: i.string(),
            symbol: i.string(),
            symbolPlacement: i.string(),
            symbolSpacing: i.boolean().optional(),
        }),
        // Add this to your schema entities
        deviceSessions: i.entity({
            appVersion: i.string().optional(),
            createdAt: i.number().indexed().optional(),
            deviceId: i.string().unique().indexed(), // The unique ID of the browser
            deviceName: i.string().optional(),
            expiresAt: i.number().indexed().optional(),
            lastSeenAt: i.number().indexed().optional(),
            userId: i.string(), // The ID of the family member logged in
            lastActiveAt: i.string(), // For auto-logout logic
            platform: i.string().indexed().optional(),
            revokedAt: i.number().indexed().optional(),
        }),
    },
    links: {
        $usersLinkedPrimaryUser: {
            forward: {
                on: '$users',
                has: 'one',
                label: 'linkedPrimaryUser',
                onDelete: 'cascade',
            },
            reverse: {
                on: '$users',
                has: 'many',
                label: 'linkedGuestUsers',
            },
        },
        allowanceEnvelopesFamilyMember: {
            forward: {
                on: 'allowanceEnvelopes',
                has: 'one',
                label: 'familyMember',
            },
            reverse: {
                on: 'familyMembers',
                has: 'many',
                label: 'allowanceEnvelopes',
            },
        },
        allowanceTransactionsDestinationEnvelope: {
            forward: {
                on: 'allowanceTransactions',
                has: 'one',
                label: 'destinationEnvelope',
            },
            reverse: {
                on: 'allowanceEnvelopes',
                has: 'many',
                label: 'incomingTransfers',
            },
        },
        allowanceTransactionsEnvelope: {
            forward: {
                on: 'allowanceTransactions',
                has: 'one',
                label: 'envelope',
            },
            reverse: {
                on: 'allowanceEnvelopes',
                has: 'many',
                label: 'transactions',
            },
        },
        allowanceTransactionsSourceEnvelope: {
            forward: {
                on: 'allowanceTransactions',
                has: 'one',
                label: 'sourceEnvelope',
            },
            reverse: {
                on: 'allowanceEnvelopes',
                has: 'many',
                label: 'outgoingTransfers',
            },
        },
        choreAssignmentsFamilyMember: {
            forward: {
                on: 'choreAssignments',
                has: 'one',
                label: 'familyMember',
            },
            reverse: {
                on: 'familyMembers',
                has: 'many',
                label: 'choreAssignments',
            },
        },
        choreCompletionsMarkedBy: {
            forward: {
                on: 'choreCompletions',
                has: 'one',
                label: 'markedBy',
            },
            reverse: {
                on: 'familyMembers',
                has: 'many',
                label: 'markedCompletions',
            },
        },
        choresAssignments: {
            forward: {
                on: 'chores',
                has: 'many',
                label: 'assignments',
            },
            reverse: {
                on: 'choreAssignments',
                has: 'one',
                label: 'chore',
            },
        },
        choresCompletions: {
            forward: {
                on: 'chores',
                has: 'many',
                label: 'completions',
            },
            reverse: {
                on: 'choreCompletions',
                has: 'one',
                label: 'chore',
            },
        },
        calendarItemsPertainsToFamilyMembers: {
            forward: {
                on: 'calendarItems',
                has: 'many',
                label: 'pertainsTo',
            },
            reverse: {
                on: 'familyMembers',
                has: 'many',
                label: 'calendarItems',
            },
        },
        calendarItemsTags: {
            forward: {
                on: 'calendarItems',
                has: 'many',
                label: 'tags',
            },
            reverse: {
                on: 'calendarTags',
                has: 'many',
                label: 'calendarItems',
            },
        },
        familyMembersAllowancePeriods: {
            forward: {
                on: 'familyMembers',
                has: 'many',
                label: 'allowancePeriods',
            },
            reverse: {
                on: 'calculatedAllowancePeriods',
                has: 'one',
                label: 'familyMember',
            },
        },
        familyMembersAssignedChores: {
            forward: {
                on: 'familyMembers',
                has: 'many',
                label: 'assignedChores',
            },
            reverse: {
                on: 'chores',
                has: 'many',
                label: 'assignees',
            },
        },
        familyMembersCompletedChores: {
            forward: {
                on: 'familyMembers',
                has: 'many',
                label: 'completedChores',
            },
            reverse: {
                on: 'choreCompletions',
                has: 'one',
                label: 'completedBy',
            },
        },
        tasksAttachments: {
            forward: {
                on: 'tasks',
                has: 'many',
                label: 'attachments',
            },
            reverse: {
                on: 'taskAttachments',
                has: 'one',
                label: 'task',
            },
        },
        tasksParentTask: {
            forward: {
                on: 'tasks',
                has: 'one',
                label: 'parentTask',
            },
            reverse: {
                on: 'tasks',
                has: 'many',
                label: 'subTasks',
            },
        },
        tasksPrerequisites: {
            forward: {
                on: 'tasks',
                has: 'many',
                label: 'prerequisites',
            },
            reverse: {
                on: 'tasks',
                has: 'many',
                label: 'subsequentTasks',
            },
        },
        taskSeriesFamilyMember: {
            forward: {
                on: 'taskSeries',
                has: 'one',
                label: 'familyMember',
            },
            reverse: {
                on: 'familyMembers',
                has: 'many',
                label: 'taskSeries',
            },
        },
        taskSeriesScheduledActivity: {
            forward: {
                on: 'taskSeries',
                has: 'one',
                label: 'scheduledActivity',
            },
            reverse: {
                on: 'chores',
                has: 'many',
                label: 'taskSeries',
            },
        },
        taskSeriesTasks: {
            forward: {
                on: 'taskSeries',
                has: 'many',
                label: 'tasks',
            },
            reverse: {
                on: 'tasks',
                has: 'one',
                label: 'taskSeries',
            },
        },
    },
    rooms: {},
});

// This helps Typescript display nicer intellisense
type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
