import { EB_Garamond } from 'next/font/google';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ebGaramond = EB_Garamond({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ebGaramond.className}>
      <body>{children}</body>
    </html>
  );
}
