import localFont from 'next/font/local';
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

// Import local Inter font
const inter = localFont({
  src: '../public/fonts/Inter_18pt-Regular.ttf',
  weight: '400',  // You can change this based on the weights you're using
  display: 'swap',
});

// Import local Inter font
const interBold = localFont({
  src: '../public/fonts/Inter_18pt-Bold.ttf',
  weight: '400',  // You can change this based on the weights you're using
  display: 'swap',
});
// Import local Inter font
const interItalic = localFont({
  src: '../public/fonts/Inter_18pt-Italic.ttf',
  weight: '400',  // You can change this based on the weights you're using
  display: 'swap',
});
// Import local Inter font
const interBoldItalic = localFont({
  src: '../public/fonts/Inter_18pt-BoldItalic.ttf',
  weight: '400',  // You can change this based on the weights you're using
  display: 'swap',
});

// Import local EB Garamond font
const ebGaramond = localFont({
  src: '../public/fonts/EBGaramond-Regular.ttf',
  weight: '400',  // Adjust this if using different weights
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}